---
apiVersion: v1
kind: ReplicationController
metadata:
  name: gocd-server
  labels:
    name: gocd-server
spec:
  replicas: 1
  selector:
    name: gocd-server
  template:
    metadata:
      labels:
        name: gocd-server
    spec:
      containers:
      - image: sennerholm/gocd-server:v17.9.1
        imagePullPolicy: Always
        name: gocd-server
        ports:
        - containerPort: 8153
          hostPort: 8153
          protocol: TCP
        - containerPort: 8154
          hostPort: 8154
          protocol: TCP
        volumeMounts:
        - name: prod-go-data
          mountPath: /godata
        - name: prod-go-data-db
          mountPath: /godata/db
        - name: ssh-key
          mountPath: /my-ssh-keys
      initContainers:
      - name: gocd-server-init
        image: busybox:glibc
        command: ['sh', '-c', 'if [ ! -f /godata/config/cruise-config.xml ]; then mkdir /godata/config; wget -O /godata/config/cruise-config.xml https://raw.githubusercontent.com/sennerholm/gce/master/go/bootstrap/cruise-config.xml; chown 1000:1000 /godata/config/cruise-config.xml; fi']
        volumeMounts:
        - name: prod-go-data
          mountPath: /godata
      restartPolicy: Always
      volumes:
        - name: prod-go-data
          gcePersistentDisk:
            pdName: prod-go-data
            fsType: ext4
        - name: prod-go-data-db
          gcePersistentDisk:
            pdName: prod-go-data-db
            fsType: ext4
        - name: ssh-key
          secret:
            secretName: ssh-key
